const CITY_DATA = {
  广州:{subtitle:'岭南烟火',center:[23.1291,113.2644],spots:[
    ['陈家祠',23.1294,113.2422,'文化','岭南建筑与木雕石雕','09:00',10,80],['永庆坊',23.1149,113.2347,'拍照','骑楼老街与粤剧艺术','10:45',0,75],['沙面岛',23.1092,113.2390,'拍照','珠江边欧式建筑群','13:30',0,80],['北京路',23.1257,113.2703,'美食','千年古道与老字号','17:00',0,110],['广东省博物馆',23.1174,113.3220,'文化','岭南自然与历史展览','10:00',0,120],['广州塔',23.1065,113.3246,'经典','城市天际线与珠江夜景','18:30',150,100],['白云山',23.1841,113.2960,'自然','城市绿肺与山顶视野','08:30',5,180],['长隆野生动物世界',22.9982,113.3269,'亲子','大型野生动物主题园区','09:30',300,360],['东山口',23.1231,113.2954,'拍照','红砖洋楼与独立小店','14:30',0,100],['荔湾湖公园',23.1210,113.2230,'自然','荔枝湾涌与岭南水乡','16:00',0,75]]},
  东莞:{subtitle:'潮玩制造',center:[23.0207,113.7518],spots:[
    ['可园博物馆',23.0338,113.7443,'文化','岭南四大名园之一','09:30',8,100],['下坝坊',23.0120,113.7390,'美食','河岸文创街区与夜生活','18:00',0,110],['鳒鱼洲文创园',23.0239,113.7387,'拍照','旧工业遗址改造街区','14:00',0,90],['东莞市博物馆',23.0228,113.7581,'文化','城市历史与莞邑文化','10:00',0,100],['同沙生态公园',22.9877,113.8060,'自然','环湖骑行与湿地风光','08:30',0,150],['松山湖风景区',22.9218,113.8913,'自然','湖岸绿道与花海','09:00',0,180],['华阳湖国家湿地公园',23.0456,113.5988,'亲子','水乡湿地与亲子骑行','09:00',0,160],['南社明清古村落',23.0852,113.8746,'文化','保存完整的宗祠古村','10:00',30,130],['隐贤山庄',22.9794,114.0087,'亲子','主题乐园与夜间表演','10:00',120,300],['厚街美食街',22.9465,113.6702,'美食','烧鹅濑粉与莞味小吃','17:30',0,100]]},
  上海:{subtitle:'海派漫游',center:[31.2304,121.4737],spots:[
    ['外滩',31.2400,121.4904,'经典','万国建筑与浦江景色','08:30',0,90],['豫园',31.2270,121.4921,'文化','江南园林与城隍庙小吃','10:30',40,110],['武康路',31.2127,121.4388,'拍照','梧桐街区与历史建筑','14:00',0,100],['上海博物馆东馆',31.2309,121.5500,'文化','中国古代艺术收藏','10:00',0,150],['陆家嘴',31.2397,121.4998,'经典','摩天楼群与城市天际线','16:30',0,100],['田子坊',31.2082,121.4688,'美食','石库门弄堂与创意店铺','15:30',0,100],['朱家角古镇',31.1074,121.0564,'自然','水乡古镇与放生桥','09:30',0,220],['上海自然博物馆',31.2369,121.4624,'亲子','大型自然科学展馆','10:00',30,180],['愚园路',31.2225,121.4328,'美食','社区小店与海派生活','11:30',0,100],['北外滩',31.2519,121.4967,'拍照','开阔滨江与日落机位','18:00',0,90]]},
  深圳:{subtitle:'山海之间',center:[22.5431,114.0579],spots:[
    ['深圳湾公园',22.5036,113.9457,'自然','滨海长廊与日落','16:30',0,120],['莲花山公园',22.5542,114.0635,'经典','俯瞰市民中心中轴线','09:00',0,100],['大芬油画村',22.6103,114.1370,'文化','画廊与艺术工作室','10:00',0,100],['南头古城',22.5397,113.9158,'美食','古城街巷与年轻店铺','14:00',0,120],['人才公园',22.5150,113.9448,'拍照','城市天际线与湖景','19:00',0,80],['大梅沙海滨公园',22.5969,114.3066,'自然','沙滩与滨海栈道','09:30',0,180],['深圳博物馆',22.5479,114.0565,'文化','改革开放与城市历史','10:00',0,120],['世界之窗',22.5360,113.9743,'亲子','微缩景观主题公园','10:00',220,300],['欢乐港湾',22.5525,113.8831,'拍照','海边摩天轮与商业街区','17:00',0,120],['盐田海鲜街',22.5905,114.2759,'美食','海鲜市场与临海餐厅','18:00',0,100]]},
  杭州:{subtitle:'湖山宋韵',center:[30.2741,120.1551],spots:[
    ['西湖断桥',30.2608,120.1487,'经典','西湖标志景点与晨间湖景','08:00',0,80],['曲院风荷',30.2496,120.1353,'自然','荷塘、古亭与苏堤风光','10:00',0,100],['灵隐寺',30.2402,120.1022,'文化','千年古刹与飞来峰','09:00',75,150],['河坊街',30.2384,120.1715,'美食','南宋街巷与杭州小吃','17:00',0,110],['中国丝绸博物馆',30.2221,120.1536,'文化','丝绸历史与服饰展览','10:00',0,120],['西溪国家湿地公园',30.2696,120.0630,'自然','湿地水网与摇橹船','09:30',80,210],['良渚博物院',30.3945,120.0528,'文化','良渚文明专题博物馆','10:00',0,150],['小河直街',30.3114,120.1474,'拍照','运河边的传统民居街区','15:00',0,90],['杭州动物园',30.2164,120.1280,'亲子','山林环境中的动物园','09:30',20,200],['北山街',30.2591,120.1418,'拍照','民国建筑与西湖落日','17:30',0,90]]}
};

const state={city:localStorage.getItem('youji-city')||'广州',days:2,pace:'normal',interest:'经典',plan:JSON.parse(localStorage.getItem('youji-plan')||'null'),saved:JSON.parse(localStorage.getItem('youji-saved')||'[]'),picked:[],activeDay:0,map:null,mapLayer:null,deferredInstall:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paceCount={slow:3,normal:4,fast:5};
const paceName={slow:'轻松',normal:'适中',fast:'紧凑'};
const slotTimes=['09:00','11:15','14:00','16:30','19:00'];
const cityNames=Object.keys(CITY_DATA);

function parseTripContext(message){
  const text=String(message||'');let origin='',destination='';
  for(const city of cityNames)if(new RegExp(`(?:从|在)${city}(?:市)?出发`).test(text))origin=city;
  const destMatch=text.match(new RegExp(`(?:去|到|前往|目的地(?:是|为)?)\\s*(${cityNames.join('|')})`));if(destMatch)destination=destMatch[1];
  if(!destination){const mentioned=cityNames.filter(city=>text.includes(city)&&city!==origin);if(mentioned.length===1)destination=mentioned[0];}
  destination=destination||state.city;
  const dm=text.match(/(?:(20\d{2})[年\/.\-])?(\d{1,2})[月\/.\-](\d{1,2})(?:日|号)?/);let date='';
  if(dm){const now=new Date(),year=Number(dm[1])||now.getFullYear();date=`${year}-${String(Number(dm[2])).padStart(2,'0')}-${String(Number(dm[3])).padStart(2,'0')}`;}
  const holiday=date&&Number(date.slice(5,7))===10&&Number(date.slice(8,10))<=7;
  const crowd=holiday||/人多|拥挤|避峰|错峰|排队|国庆|十一/.test(text);
  const days=Math.max(1,Math.min(4,Number((text.match(/(\d)\s*天/)||[])[1])||Number($('#days').value)||2));
  return{origin,destination,date,crowd,days};
}
function toMinutes(time){const[h,m]=time.split(':').map(Number);return h*60+m;}
function fromMinutes(value){value=Math.min(value,23*60+45);return`${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`;}
function dateLabel(date,offset){if(!date)return`第${offset+1}天`;const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+offset);return`${d.getMonth()+1}月${d.getDate()}日`;}
function makeDetailedSchedule(groups,context={}){return groups.map((group,day)=>{const intercity=day===0&&context.origin&&context.origin!==context.destination;let cursor=context.crowd?(intercity?510:450):540;if(group[0])cursor=Math.max(cursor,toMinutes(group[0][5]));const items=group.map((spot,i)=>{let travel=0;if(i){travel=Math.max(15,Math.min(75,Math.round(distance(group[i-1],spot)/22*60+10)));cursor+=travel;if(cursor>=660&&cursor<780)cursor=780;}const start=fromMinutes(cursor),end=fromMinutes(cursor+spot[7]);cursor+=spot[7]+(i===0?15:20);const firstTravel=intercity?`从${context.origin}出发，建议06:30前启程并按实际车次预留进站时间`:(day>0?'从住宿地出发，建议提前15分钟到达':'建议提前15分钟到达');return{name:spot[0],start,end,travel:i?`从上一站约${travel}分钟`:firstTravel,reason:context.crowd&&i===0?'热门日期优先安排首站，尽量赶在客流高峰前进入':`与前后地点距离较近，适合安排在第${day+1}天`};});return{day:day+1,label:dateLabel(context.date,day),items};});}

function renderCities(){ $('#cityStrip').innerHTML=Object.entries(CITY_DATA).map(([name,c])=>`<button class="city-button ${name===state.city?'selected':''}" data-city="${name}" type="button"><b>${name}</b><small>${c.subtitle}</small></button>`).join('');if($('#aiCityLabel'))$('#aiCityLabel').textContent=`当前：${state.city}`; }
function setCity(city){state.city=city;state.picked=[];localStorage.setItem('youji-city',city);renderCities();renderPlaceOptions();if($('#aiCityLabel'))$('#aiCityLabel').textContent=`当前：${city}`;}
function distance(a,b){const r=Math.PI/180,dLat=(b[1]-a[1])*r,dLng=(b[2]-a[2])*r,x=Math.sin(dLat/2)**2+Math.cos(a[1]*r)*Math.cos(b[1]*r)*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function orderNearest(spots){if(spots.length<2)return [...spots];const center=['中心',...CITY_DATA[state.city].center];const left=[...spots],ordered=[];let current=center;while(left.length){let best=0;for(let i=1;i<left.length;i++)if(distance(current,left[i])<distance(current,left[best]))best=i;current=left.splice(best,1)[0];ordered.push(current);}return ordered;}
function groupByDays(spots,days){const ordered=orderNearest(spots),groups=Array.from({length:days},()=>[]);const perDay=Math.ceil(ordered.length/days);ordered.forEach((s,i)=>groups[Math.min(days-1,Math.floor(i/perDay))].push(s));groups.forEach(group=>group.sort((a,b)=>toMinutes(a[5])-toMinutes(b[5])));return groups;}
function generatePlan(){
  state.days=Number($('#days').value);state.pace=$('#pace').value;
  const base=[...CITY_DATA[state.city].spots];
  const prioritized=base.sort((a,b)=>Number(b[3]===state.interest)-Number(a[3]===state.interest));
  const needed=Math.min(prioritized.length,state.days*paceCount[state.pace]);
  const chosen=prioritized.slice(0,needed);
  const groups=groupByDays(chosen,state.days);
  const context={destination:state.city,date:'',crowd:false};state.plan={city:state.city,days:state.days,pace:state.pace,interest:state.interest,groups,schedule:makeDetailedSchedule(groups,context),createdAt:Date.now()};
  state.activeDay=0;localStorage.setItem('youji-plan',JSON.stringify(state.plan));renderTrip();showView('trip');showToast('路线已生成，可以随时调整');
}
function renderPlaceOptions(query=''){const host=$('#placeOptions');if(!host)return;const q=query.trim().toLowerCase();const spots=CITY_DATA[state.city].spots.filter(s=>!q||`${s[0]}${s[3]}${s[4]}`.toLowerCase().includes(q));host.innerHTML=spots.map(s=>{const on=state.picked.includes(s[0]);return `<label class="place-option ${on?'selected':''}"><input type="checkbox" value="${s[0]}" ${on?'checked':''}><div><b>${s[0]}</b><small>${s[4]} · 约${s[7]}分钟</small></div><em>${s[3]}</em></label>`}).join('')||'<div class="empty-card">没有找到相关地点</div>';$('#pickCount').textContent=`已选 ${state.picked.length} 个`;}
function buildCustomPlan(){if(state.picked.length<2){showToast('请至少选择2个地点');return;}state.days=Number($('#days').value);state.pace=$('#pace').value;const selected=CITY_DATA[state.city].spots.filter(s=>state.picked.includes(s[0])),groups=groupByDays(selected,state.days),context={destination:state.city,date:'',crowd:false};state.plan={city:state.city,days:state.days,pace:state.pace,interest:'自选地点',groups,schedule:makeDetailedSchedule(groups,context),createdAt:Date.now(),reason:'已根据地点距离进行就近分组，减少折返，并为交通和用餐预留时间。'};state.activeDay=0;localStorage.setItem('youji-plan',JSON.stringify(state.plan));$('#placePicker').hidden=true;renderTrip();showView('trip');showToast('已生成自选地点线路');}
function renderTrip(){
  if(!state.plan){$('#timeline').innerHTML='<div class="empty-card"><span>🧭</span>先从首页生成一条旅行路线</div>';return;}
  const p=state.plan;$('#tripTitle').textContent=`${p.city}行程`;$('#tripMeta').textContent=`${p.days}日 · ${paceName[p.pace]} · ${p.interest}`;
  const all=p.groups.flat();$('#spotCount').textContent=all.length;$('#walkTotal').textContent=`${(all.length*1.15).toFixed(1)} km`;$('#budgetTotal').textContent=`¥${all.reduce((n,s)=>n+s[6],0)+p.days*180}`;
  $('#dayTabs').innerHTML=p.groups.map((_,i)=>`<button type="button" class="day-tab ${i===state.activeDay?'active':''}" data-day="${i}" role="tab">${p.schedule?.[i]?.label||`第${i+1}天`}</button>`).join('');
  const group=p.groups[state.activeDay]||[];
  const advice=p.advice?.length?`<div class="trip-advice"><b>出行建议</b>${p.advice.map(x=>`<span>· ${esc(x)}</span>`).join('')}</div>`:'';
  $('#timeline').innerHTML=(p.reason?`<div class="route-reason">${esc(p.reason)}</div>`:'')+advice+(group.map((s,i)=>stopHTML(s,i,p.schedule?.[state.activeDay]?.items?.[i])).join('')||'<div class="empty-card">这一天暂时没有地点</div>');
}
function stopHTML(s,i,detail){const key=`${state.plan.city}-${s[0]}`;const saved=state.saved.some(x=>x.key===key);const nav=`https://uri.amap.com/navigation?to=${s[2]},${s[1]},${encodeURIComponent(s[0])}&mode=walk&callnative=1`;const time=detail?`${detail.start}–${detail.end}`:(slotTimes[i]||s[5]);
  return `<article class="stop-card"><time class="stop-time">${time}</time><div class="stop-body"><h3>${i+1}. ${s[0]}</h3><p>${s[4]}</p>${detail?`<div class="stop-detail"><b>${esc(detail.travel)}</b><span>${esc(detail.reason)}</span></div>`:''}<div class="stop-tags"><span>${s[3]}</span><span>约${s[7]}分钟</span><span>${s[6]?`门票约¥${s[6]}`:'免费'}</span></div><div class="stop-actions"><a href="${nav}" target="_blank" rel="noopener">开始导航</a><button type="button" class="save-spot ${saved?'saved':''}" data-name="${s[0]}">${saved?'已收藏':'收藏'}</button></div></div></article>`;}
function renderSaved(){const list=$('#savedList');if(!state.saved.length){list.innerHTML='<div class="empty-card"><span>♡</span>还没有收藏地点<br><small>在行程中看到喜欢的地方就收下吧</small></div>';return;}list.innerHTML=state.saved.map(x=>`<article class="saved-card"><span class="saved-icon">${x.category==='美食'?'🥢':x.category==='自然'?'🌿':x.category==='文化'?'🏛️':'📍'}</span><div><b>${x.name}</b><small>${x.city} · ${x.category}</small></div><button type="button" data-remove="${x.key}" aria-label="删除收藏">×</button></article>`).join('');}
function toggleSave(name){const spot=CITY_DATA[state.plan.city].spots.find(s=>s[0]===name);const key=`${state.plan.city}-${name}`;const ix=state.saved.findIndex(x=>x.key===key);if(ix>=0){state.saved.splice(ix,1);showToast('已取消收藏');}else{state.saved.push({key,name,city:state.plan.city,category:spot[3],lat:spot[1],lng:spot[2]});showToast('已加入收藏');}localStorage.setItem('youji-saved',JSON.stringify(state.saved));renderTrip();renderSaved();}
function renderMap(){
  if(!state.plan)return;const spots=state.plan.groups[state.activeDay]||[];$('#mapTitle').textContent=`${state.plan.city} · 第${state.activeDay+1}天`;
  $('#mapRouteList').innerHTML=spots.map((s,i)=>{const d=state.plan.schedule?.[state.activeDay]?.items?.[i];return`<div class="map-route-item"><span class="num">${i+1}</span><div><b>${s[0]}</b><small>${d?`${esc(d.start)}–${esc(d.end)}`:(slotTimes[i]||s[5])} · ${s[3]}</small></div><a target="_blank" rel="noopener" href="https://uri.amap.com/navigation?to=${s[2]},${s[1]},${encodeURIComponent(s[0])}&mode=walk&callnative=1">导航</a></div>`;}).join('');
  if(!window.L){$('#mapFallback').hidden=false;return;}if(!state.map){state.map=L.map('map',{zoomControl:false,attributionControl:true});L.control.zoom({position:'bottomright'}).addTo(state.map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(state.map);}if(state.mapLayer)state.map.removeLayer(state.mapLayer);state.mapLayer=L.layerGroup().addTo(state.map);const pts=[];spots.forEach((s,i)=>{pts.push([s[1],s[2]]);const icon=L.divIcon({className:'marker-badge',html:String(i+1),iconSize:[30,30],iconAnchor:[15,15]});L.marker([s[1],s[2]],{icon}).bindPopup(`<b>${s[0]}</b><br>${s[4]}`).addTo(state.mapLayer);});if(pts.length>1)L.polyline(pts,{color:'#ff7958',weight:4,opacity:.9,dashArray:'8 7'}).addTo(state.mapLayer);state.map.fitBounds(pts.length?pts:[CITY_DATA[state.plan.city].center],{padding:[70,70],maxZoom:13});setTimeout(()=>state.map.invalidateSize(),80);
}
function showView(name){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`).classList.add('active');$$('.bottom-nav a').forEach(a=>a.classList.toggle('active',a.dataset.view===name));location.hash=name;if(name==='trip')renderTrip();if(name==='map')renderMap();if(name==='saved')renderSaved();window.scrollTo(0,0);}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),1900);}
function sharePlan(){if(!state.plan)return;const p=state.plan;const text=`我的${p.city}${p.days}日行程：\n`+p.groups.map((g,i)=>`第${i+1}天：${g.map(s=>s[0]).join(' → ')}`).join('\n');if(navigator.share)navigator.share({title:`${p.city}旅行计划`,text,url:location.href}).catch(()=>{});else navigator.clipboard?.writeText(text).then(()=>showToast('行程已复制'));}
function appendMessage(role,html,extra=''){const el=document.createElement('article');el.className=`chat-message ${role} ${extra}`;el.innerHTML=`<span>${role==='user'?'你':'✦'}</span><p>${html}</p>`;$('#chatThread').appendChild(el);el.scrollIntoView({behavior:'smooth',block:'end'});return el;}
function localAiPlan(message,context=parseTripContext(message)){
  const text=message.toLowerCase();let interest=['美食','自然','文化','拍照','亲子'].find(x=>text.includes(x));
  if(!interest)interest=/孩子|小孩|带娃/.test(text)?'亲子':/古村|博物馆|历史|人文|父母|老人/.test(text)?'文化':/海边|湖|山|公园|湿地/.test(text)?'自然':/吃|小吃|老店/.test(text)?'美食':'经典';
  const easy=/少走|轻松|老人|父母/.test(text),limit=easy||context.crowd?3:4,all=CITY_DATA[context.destination].spots;
  const named=all.filter(s=>text.includes(s[0]));const keyword=all.filter(s=>(/古村/.test(text)&&/古村/.test(s[0]+s[4]))||(/自然|公园|湖|山|湿地/.test(text)&&s[3]==='自然')||(/美食|小吃|吃/.test(text)&&s[3]==='美食')||(/拍照|出片/.test(text)&&s[3]==='拍照'));
  const preferred=all.filter(s=>s[3]===interest);const pool=[...named,...keyword,...preferred,...all.filter(s=>!context.crowd||s[3]!=='经典'),...all];
  const unique=[...new Map(pool.map(s=>[s[0],s])).values()].slice(0,Math.min(all.length,context.days*limit)),groups=groupByDays(unique,context.days),schedule=makeDetailedSchedule(groups,context);
  const dateText=context.date?`${Number(context.date.slice(5,7))}月${Number(context.date.slice(8,10))}日开始`:'按你选择的日期';
  const advice=[context.crowd?(context.origin&&context.origin!==context.destination?'首日跨城后直接进入首站；住在目的地后的早晨优先安排户外地点并尽早出发。':'首个热门地点尽量在开放后尽快进入，11:00前离开核心客流区。'):'每天保留15至20分钟机动时间。',context.crowd?'午餐建议11:15前或13:30后，预约项目提前确认时段。':'门票和开放时间请在出发前一天复核。',context.origin&&context.origin!==context.destination?`从${context.origin}前往${context.destination}，建议优先选择早班城际或高铁，并预留进站时间。`:'优先使用公共交通，减少停车和找车位时间。'];
  return{reply:`目的地已识别为${context.destination}，出发地为${context.origin||'未指定'}。我按${dateText}、${context.days}天、${easy?'轻松':'适中'}节奏安排，并把${context.crowd?'节假日避峰':'交通衔接'}放在优先位置。`,route:groups.flat().map(s=>s[0]),trip_days:context.days,schedule,advice,destination:context.destination,origin:context.origin,date:context.date,mode:'local'};
}
function applyAiPlan(result,context={}){const destination=result.destination||context.destination||state.city;if(!CITY_DATA[destination])return;setCity(destination);const days=Math.max(1,Math.min(4,result.trip_days||result.days||context.days||2));let groups=[];if(Array.isArray(result.schedule)&&result.schedule.length){groups=result.schedule.slice(0,days).map(day=>(day.items||[]).map(item=>CITY_DATA[destination].spots.find(s=>s[0]===item.name)).filter(Boolean));}if(!groups.flat().length){const spots=(result.route||[]).map(name=>CITY_DATA[destination].spots.find(s=>s[0]===name)).filter(Boolean);groups=groupByDays(spots,days);}const schedule=Array.isArray(result.schedule)&&result.schedule.length?result.schedule:makeDetailedSchedule(groups,{...context,destination});state.plan={city:destination,origin:result.origin||context.origin||'',date:result.date||context.date||'',days,pace:'normal',interest:'AI精细规划',groups,schedule,advice:result.advice||[],createdAt:Date.now(),reason:result.reply};state.activeDay=0;localStorage.setItem('youji-plan',JSON.stringify(state.plan));}
function aiResultHTML(result){const schedule=(result.schedule||[]).map(day=>`<section class="ai-day"><b>${esc(day.label||`第${day.day}天`)}</b>${(day.items||[]).map(item=>`<div><time>${esc(item.start)}–${esc(item.end)}</time><span>${esc(item.name)}</span><small>${esc(item.travel||'')}</small></div>`).join('')}</section>`).join('');const advice=(result.advice||[]).map(x=>`<li>${esc(x)}</li>`).join('');return`${esc(result.reply)}<span class="ai-result"><b>精细时间线路</b>${schedule}${advice?`<strong>出行建议</strong><ul>${advice}</ul>`:''}<button type="button" data-use-ai>采用完整方案</button></span>`;}
async function askAI(message){const context=parseTripContext(message);if(context.destination!==state.city)setCity(context.destination);const loading=appendMessage('assistant',`正在识别出发地和目的地，并结合${context.date||'出行日期'}、客流和地点距离安排时间……`,'loading');const payload={city:context.destination,origin:context.origin,date:context.date,crowd:context.crowd,days:context.days,message,spots:CITY_DATA[context.destination].spots.map(s=>({name:s[0],lat:s[1],lng:s[2],category:s[3],description:s[4],price:s[6],minutes:s[7]}))};try{const response=await fetch('/api/plan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('AI unavailable');const result=await response.json();loading.remove();applyAiPlan(result,context);appendMessage('assistant',aiResultHTML(result));}catch(error){const result=localAiPlan(message,context);loading.remove();applyAiPlan(result,context);appendMessage('assistant',`${aiResultHTML(result)}\n当前使用本地精细规划；配置模型密钥后会自动切换为 GPT-5.6。`);}}

document.addEventListener('click',e=>{const city=e.target.closest('[data-city]');if(city)setCity(city.dataset.city);const chip=e.target.closest('[data-interest]');if(chip){$$('[data-interest]').forEach(x=>x.classList.remove('selected'));chip.classList.add('selected');state.interest=chip.dataset.interest;}const theme=e.target.closest('[data-theme]');if(theme){state.interest=theme.dataset.theme;$$('[data-interest]').forEach(x=>x.classList.toggle('selected',x.dataset.interest===state.interest));$('#plannerForm').scrollIntoView({behavior:'smooth',block:'center'});}const tab=e.target.closest('[data-day]');if(tab){state.activeDay=Number(tab.dataset.day);renderTrip();}const saver=e.target.closest('.save-spot');if(saver)toggleSave(saver.dataset.name);const rem=e.target.closest('[data-remove]');if(rem){state.saved=state.saved.filter(x=>x.key!==rem.dataset.remove);localStorage.setItem('youji-saved',JSON.stringify(state.saved));renderSaved();}const prompt=e.target.closest('[data-prompt]');if(prompt){$('#aiPrompt').value=prompt.dataset.prompt;$('#aiPrompt').focus();}if(e.target.closest('[data-use-ai]')){renderTrip();showView('trip');showToast('已采用 AI 推荐路线');}const nav=e.target.closest('[data-view]');if(nav){e.preventDefault();showView(nav.dataset.view);}});
$('#plannerForm').addEventListener('submit',e=>{e.preventDefault();generatePlan();});
$('#optimizeBtn').addEventListener('click',()=>{if(!state.plan)return;state.plan.groups[state.activeDay]=orderNearest(state.plan.groups[state.activeDay]);localStorage.setItem('youji-plan',JSON.stringify(state.plan));renderTrip();showToast('已按距离重新优化顺序');});
$('#shareBtn').addEventListener('click',sharePlan);
$('#choosePlacesBtn').addEventListener('click',()=>{$('#placePicker').hidden=false;renderPlaceOptions();});
$('#closePicker').addEventListener('click',()=>{$('#placePicker').hidden=true;});
$('#placeSearch').addEventListener('input',e=>renderPlaceOptions(e.target.value));
$('#placeOptions').addEventListener('change',e=>{if(!e.target.matches('input[type=checkbox]'))return;state.picked=e.target.checked?[...state.picked,e.target.value]:state.picked.filter(x=>x!==e.target.value);renderPlaceOptions($('#placeSearch').value);});
$('#clearPicks').addEventListener('click',()=>{state.picked=[];renderPlaceOptions($('#placeSearch').value);});
$('#buildCustomPlan').addEventListener('click',buildCustomPlan);
$('#aiForm').addEventListener('submit',async e=>{e.preventDefault();const input=$('#aiPrompt'),message=input.value.trim();if(!message)return;appendMessage('user',message.replace(/[<>]/g,''));input.value='';$('#aiSend').disabled=true;await askAI(message);$('#aiSend').disabled=false;});
$('#locateBtn').addEventListener('click',()=>{if(!navigator.geolocation){showToast('当前设备不支持定位');return;}navigator.geolocation.getCurrentPosition(pos=>{if(state.map)state.map.setView([pos.coords.latitude,pos.coords.longitude],14);showToast('已定位到当前位置');},()=>showToast('请允许浏览器访问位置'));});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;$('#installBtn').hidden=false;});
$('#installBtn').addEventListener('click',async()=>{if(state.deferredInstall){state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;$('#installBtn').hidden=true;}else showToast('请点 Safari 分享，再选“添加到主屏幕”');});
window.addEventListener('hashchange',()=>showView(location.hash.slice(1)||'home'));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
function registerWebMCP(){
  const context=document.modelContext;if(!context?.registerTool)return;
  const controller=new AbortController();
  const cities=Object.keys(CITY_DATA);
  Promise.resolve(context.registerTool({name:'create_travel_plan',title:'生成五城旅行路线',description:'为广州、东莞、上海、深圳或杭州生成1至4天的旅行路线，并立即显示在应用中。',inputSchema:{type:'object',properties:{city:{type:'string',enum:cities},days:{type:'integer',minimum:1,maximum:4},pace:{type:'string',enum:['slow','normal','fast']},interest:{type:'string',enum:['经典','美食','自然','文化','拍照','亲子']}},required:['city','days'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!cities.includes(input.city)||!Number.isInteger(input.days)||input.days<1||input.days>4)throw new Error('城市或天数无效');setCity(input.city);$('#days').value=String(input.days);$('#pace').value=input.pace||'normal';state.interest=input.interest||'经典';generatePlan();return{city:state.plan.city,days:state.plan.days,stops:state.plan.groups.flat().map(s=>s[0])};}},{signal:controller.signal})).catch(()=>{});
  Promise.resolve(context.registerTool({name:'read_current_travel_plan',title:'读取当前旅行路线',description:'读取应用中当前显示的城市、天数和每日地点，不修改行程。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){return state.plan?{city:state.plan.city,days:state.plan.days,groups:state.plan.groups.map(g=>g.map(s=>s[0]))}:{plan:null};}},{signal:controller.signal})).catch(()=>{});
}
registerWebMCP();
renderCities();renderSaved();renderPlaceOptions();if(state.plan)renderTrip();showView(['home','trip','map','ai','saved'].includes(location.hash.slice(1))?location.hash.slice(1):'home');
